---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Copy Nginx configuration from template
  template:
    src: app.conf.j2
    dest: /etc/nginx/sites-available/app.conf
  notify: reload nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/app.conf
    dest: /etc/nginx/sites-enabled/app.conf
    state: link
  notify: reload nginx

- name: Allow Nginx HTTP traffic in UFW
  ufw:
    rule: allow
    name: 'Nginx Full'

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
